# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-04 09:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='My_Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='opis')),
                ('quantity', models.IntegerField(default=1, verbose_name='ilość')),
                ('date_sent', models.DateTimeField(default=datetime.datetime(2017, 9, 4, 9, 21, 42, 810534), verbose_name='wysłano:')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='produkt')),
                ('price', models.IntegerField(verbose_name='cena')),
                ('catgory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Category', verbose_name='kategoria')),
            ],
        ),
    ]
