# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-04 10:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_groups',
            name='groups',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 4, 10, 39, 43, 714004), verbose_name='wysłano:'),
        ),
        migrations.DeleteModel(
            name='My_Groups',
        ),
    ]
