# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-04 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20170904_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catgory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 4, 18, 5, 23, 685556), verbose_name='wysłano:'),
        ),
    ]
