# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-07 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20170904_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Product', verbose_name='produkt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 7, 9, 1, 28, 948262), verbose_name='wysłano'),
        ),
    ]
